/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf --transform
Author: Spark (https://sketchfab.com/muammar.yacoob)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arduino-uno-low-poly-43cebeb50dc14ab490b553f0a0077eb9
Title: Arduino UNO - Low Poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/assets/3dModels/arduino/scene-transformed.glb"
  );

  return (
    <group {...props} dispose={null}>
      <group
        position={[-3, 5.13, 8]} /* 
        rotation={[0, -Math.PI / 4, 0]} */
        scale={(0.5, 0.5, 0.5)}
      >
        <mesh
          geometry={nodes.Arduino_Blue2_FiberGlass_0.geometry}
          material={materials.FiberGlass}
        />
        <mesh
          geometry={nodes.Arduino_Blue2_Metal_0.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Arduino_Blue2_Back_0.geometry}
          material={materials.Back}
        />
        <mesh
          geometry={nodes.Arduino_Blue2_LED_0.geometry}
          material={materials.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
