/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf --transform
Author: zoe.goodward (https://sketchfab.com/zoe.goodward)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/line-follower-robot-11bf9b71d5f34517b404d12c74ddb506
Title: Line Follower Robot
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/assets/3dModels/lineFollower/scene-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group position={[-2.8, 0, -4.67]} rotation={[0, -6.5, 0]}>
        <group rotation={[0.4, Math.PI, -Math.PI / 15]}>
          <mesh
            geometry={nodes.base__0.geometry}
            material={materials.base__0}
            position={[-1.29, 0.14, 1.67]}
          />
          <mesh
            geometry={nodes.top__0.geometry}
            material={materials.base__0}
            position={[-1.4, 2.44, 0.73]}
          />
          <group
            position={[3.71, 3.11, 6.8]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          >
            <mesh geometry={nodes.__0.geometry} material={materials.material} />
            <mesh
              geometry={nodes.__0_1.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_2.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_3.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_4.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_5.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_6.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_7.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_8.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_9.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_10.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_11.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_12.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_13.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_14.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_15.geometry}
              material={materials.material_2}
            />
            <mesh
              geometry={nodes.__0_16.geometry}
              material={materials.material_3}
            />
            <mesh
              geometry={nodes.__0_17.geometry}
              material={materials.material_3}
            />
            <mesh
              geometry={nodes.__0_18.geometry}
              material={materials.material_4}
            />
            <mesh
              geometry={nodes.__0_19.geometry}
              material={materials.material_4}
            />
            <mesh
              geometry={nodes.__0_20.geometry}
              material={materials.material_4}
            />
            <mesh
              geometry={nodes.__0_21.geometry}
              material={materials.material_4}
            />
            <mesh
              geometry={nodes.__0_22.geometry}
              material={materials.material_4}
            />
            <mesh
              geometry={nodes.__0_23.geometry}
              material={materials.material_4}
            />
            <mesh
              geometry={nodes.__0_24.geometry}
              material={materials.material_4}
            />
            <mesh
              geometry={nodes.__0_25.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_26.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_27.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_28.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_29.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_30.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_31.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_32.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_33.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_34.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_35.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_36.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_37.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_38.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_39.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_40.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_41.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_42.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_43.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_44.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_45.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_46.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_47.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_48.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_49.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_50.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_51.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_52.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_53.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_54.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_55.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_56.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_57.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_58.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_59.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_60.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_61.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_62.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_63.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_64.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_65.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_66.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_67.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_68.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_69.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_70.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_71.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_72.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_73.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_74.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_75.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_76.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_77.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_78.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_79.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_80.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_81.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_82.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_83.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_84.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_85.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_86.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_87.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_88.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_89.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_90.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_91.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_92.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_93.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_94.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_95.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_96.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_97.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_98.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_99.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_100.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_101.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_102.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_103.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_104.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_105.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_106.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_107.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_108.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_109.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_110.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_111.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_112.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_113.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_114.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_115.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_116.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_117.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_118.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_119.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_120.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_121.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_122.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_123.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_124.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_125.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_126.geometry}
              material={materials.material_7}
            />
            <mesh
              geometry={nodes.__0_127.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_128.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_129.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_130.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_131.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_132.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_133.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_134.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_135.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_136.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_137.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_138.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_139.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_140.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_141.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_142.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_143.geometry}
              material={materials.material_9}
            />
            <mesh
              geometry={nodes.__0_144.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_145.geometry}
              material={materials.material_10}
            />
            <mesh
              geometry={nodes.__0_146.geometry}
              material={materials.material_10}
            />
            <mesh
              geometry={nodes.__0_147.geometry}
              material={materials.material_11}
            />
            <mesh
              geometry={nodes.__0_148.geometry}
              material={materials["0_10"]}
            />
            <mesh
              geometry={nodes.__0_149.geometry}
              material={materials["0_10"]}
            />
          </group>
          <group
            position={[-8.44, -0.64, -6.07]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.__0_150.geometry}
              material={materials["0_11"]}
            />
            <mesh
              geometry={nodes.__0_151.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_152.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_153.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_154.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_155.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_156.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_157.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_158.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_159.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_160.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_161.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_162.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_163.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_164.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_165.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_166.geometry}
              material={materials.material_8}
            />
            <mesh
              geometry={nodes.__0_167.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_168.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_169.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_170.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_171.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_172.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_173.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_174.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_175.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_176.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_177.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_178.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_179.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_180.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_181.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_182.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_183.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_184.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_185.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_186.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_187.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_188.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_189.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_190.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_191.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_192.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_193.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_194.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_195.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_196.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_197.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_198.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_199.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_200.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_201.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_202.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_203.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_204.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_205.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_206.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_207.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_208.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_209.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_210.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_211.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_212.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_213.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_214.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_215.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_216.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_217.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_218.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_219.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_220.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_221.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_222.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_223.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_224.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_225.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_226.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_227.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_228.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_229.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_230.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_231.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_232.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_233.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_234.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_235.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_236.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_237.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_238.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_239.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_240.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_241.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_242.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_243.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_244.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_245.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_246.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_247.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_248.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_249.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_250.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_251.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_252.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_253.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_254.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_255.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_256.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_257.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_258.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_259.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_260.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_261.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_262.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_263.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_264.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_265.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_266.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_267.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_268.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_269.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_270.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_271.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_272.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_273.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_274.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_275.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_276.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_277.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_278.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_279.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_280.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_281.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_282.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_283.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_284.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_285.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_286.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_287.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_288.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_289.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_290.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_291.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_292.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_293.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_294.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_295.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_296.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_297.geometry}
              material={materials.material_5}
            />
            <mesh
              geometry={nodes.__0_298.geometry}
              material={materials.material_6}
            />
            <mesh
              geometry={nodes.__0_299.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_300.geometry}
              material={materials["0_12"]}
            />
            <mesh
              geometry={nodes.__0_301.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_302.geometry}
              material={materials["0_13"]}
            />
            <mesh
              geometry={nodes.__0_303.geometry}
              material={materials["0_13"]}
            />
            <mesh
              geometry={nodes.__0_304.geometry}
              material={materials["0_14"]}
            />
          </group>
          <mesh
            geometry={nodes.battery__0.geometry}
            material={materials.battery__0}
            position={[-1.4, 1.44, -2.67]}
          />
          <group position={[6.14, 0.94, 1.63]} rotation={[0, Math.PI / 2, 0]}>
            <mesh
              geometry={nodes.__0_305.geometry}
              material={materials["0_15"]}
            />
            <mesh
              geometry={nodes.__0_306.geometry}
              material={materials["0_16"]}
            />
            <mesh
              geometry={nodes.__0_307.geometry}
              material={materials["0_17"]}
            />
            <mesh
              geometry={nodes.__0_308.geometry}
              material={materials["0_17"]}
            />
            <mesh
              geometry={nodes.__0_309.geometry}
              material={materials["0_17"]}
            />
            <mesh
              geometry={nodes.__0_310.geometry}
              material={materials["0_17"]}
            />
            <mesh
              geometry={nodes.__0_311.geometry}
              material={materials["0_17"]}
            />
          </group>
          <group position={[-8.95, 0.94, 1.63]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh
              geometry={nodes.__0_312.geometry}
              material={materials["0_15"]}
            />
            <mesh
              geometry={nodes.__0_313.geometry}
              material={materials["0_16"]}
            />
            <mesh
              geometry={nodes.__0_314.geometry}
              material={materials["0_17"]}
            />
            <mesh
              geometry={nodes.__0_315.geometry}
              material={materials["0_17"]}
            />
            <mesh
              geometry={nodes.__0_316.geometry}
              material={materials["0_17"]}
            />
            <mesh
              geometry={nodes.__0_317.geometry}
              material={materials["0_17"]}
            />
            <mesh
              geometry={nodes.__0_318.geometry}
              material={materials["0_17"]}
            />
          </group>
          <mesh
            geometry={nodes.bracket__0.geometry}
            material={materials.bracket__0}
            position={[6.22, 0.44, 1.63]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.bracket__0_1.geometry}
            material={materials.bracket__0}
            position={[-9.03, 0.44, 1.63]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <group
            position={[-1.41, -0.07, -4.85]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.__0_319.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_320.geometry}
              material={materials["0_18"]}
            />
          </group>
          <group position={[7.43, 0.94, 1.63]} rotation={[0, Math.PI / 2, 0]}>
            <mesh
              geometry={nodes.__0_321.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_322.geometry}
              material={materials["0_19"]}
            />
          </group>
          <group
            position={[-10.24, 0.94, 1.63]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.__0_323.geometry}
              material={materials.base__0}
            />
            <mesh
              geometry={nodes.__0_324.geometry}
              material={materials["0_19"]}
            />
          </group>
          <mesh
            geometry={nodes["DIN_EN_ISO_4762_-_M2_x_10__0"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-8.3, 0.13, 2.53]}
            rotation={[0, -0.99, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["DIN_EN_ISO_4762_-_M2_x_10__0_1"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[5.5, 0.13, 2.53]}
            rotation={[Math.PI, 0.26, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_30(2)__0"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 0.05, -1.97]}
            rotation={[0, -0.05, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_30(2)__0_1"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 0.05, 3.53]}
            rotation={[0, 0.99, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_30(2)__0_2"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 0.05, 3.53]}
            rotation={[0, 0.99, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_30(2)__0_3"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 0.05, -1.97]}
            rotation={[Math.PI, Math.PI / 3, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_12(2)__0"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 2.34, 3.53]}
            rotation={[-Math.PI, -Math.PI / 6, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_12(2)__0_1"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 2.35, 3.53]}
            rotation={[-Math.PI, -Math.PI / 6, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_12(2)__0_2"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 2.34, -1.97]}
            rotation={[-Math.PI, -Math.PI / 6, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_12(2)__0_3"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 2.34, -1.97]}
            rotation={[-Math.PI, -Math.PI / 6, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_16(2)__0"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, -0.68, -7.47]}
            rotation={[-Math.PI, -1.3, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["AS_1427_-_M3_x_16(2)__0_1"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, -0.68, -7.47]}
            rotation={[-Math.PI, -1.3, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 2.74, -1.97]}
            rotation={[Math.PI, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_1"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 0.44, 3.53]}
            rotation={[-Math.PI, -0.58, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_2"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 0.44, -1.97]}
            rotation={[-Math.PI, -0.58, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_3"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 2.74, -1.97]}
            rotation={[Math.PI, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_4"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 2.74, -1.97]}
            rotation={[Math.PI, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_5"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 0.53, 3.53]}
            rotation={[Math.PI, -0.58, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_6"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 3.11, 3.53]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_7"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 3.11, -1.97]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_8"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 2.44, -1.97]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_9"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 0.53, -1.97]}
            rotation={[Math.PI, -0.58, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_10"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 3.11, 3.53]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_11"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 2.83, -1.97]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_12"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 2.44, 3.53]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_13"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 2.83, 3.53]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_14"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 2.83, 3.53]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_15"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 2.35, -1.97]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_16"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 0.14, 3.53]}
            rotation={[Math.PI, 0.58, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_17"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 2.44, 3.53]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_18"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 3.11, -1.97]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_19"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 0.14, 3.53]}
            rotation={[Math.PI, 0.58, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_20"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 0.14, -1.97]}
            rotation={[Math.PI, 0.58, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_21"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 0.14, -1.97]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_22"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 2.83, 3.53]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 3.07, 3.53]}
            rotation={[Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_1"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 3.07, -1.97]}
            rotation={[Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_2"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 3.07, 3.53]}
            rotation={[Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_3"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 0.77, 3.53]}
            rotation={[0, -0.47, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_4"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 0.77, 3.53]}
            rotation={[0, -0.47, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_5"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 3.07, -1.97]}
            rotation={[0, -Math.PI / 3, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_6"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 0.77, -1.97]}
            rotation={[0, -0.47, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_7"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 0.53, -1.97]}
            rotation={[0, 0.58, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_8"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 2.35, 3.53]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_9"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 2.35, 3.53]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_10"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[1.4, 2.35, -1.97]}
            rotation={[-Math.PI, Math.PI / 3, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_11"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-4.2, 2.35, -1.97]}
            rotation={[Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_23"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 0.53, -7.47]}
            rotation={[Math.PI, 0.58, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_24"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, -0.55, -7.47]}
            rotation={[0, -0.78, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_25"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 2.44, -1.97]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_26"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, -0.55, -7.47]}
            rotation={[0, -0.78, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_27"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 0.53, -7.47]}
            rotation={[Math.PI, 0.58, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_28"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 0.05, -7.47]}
            rotation={[0, -0.27, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_29"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 0.05, -7.47]}
            rotation={[0, -0.27, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_30"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 2.44, 3.53]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_31"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 2.44, -1.97]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_32"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 2.83, 3.53]}
            rotation={[Math.PI, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B1822M_-_3_N__0_33"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 2.44, 3.53]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_12"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 2.83, -1.97]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_13"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 3.42, 3.53]}
            rotation={[-Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_14"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 3.44, 3.53]}
            rotation={[-Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_15"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 3.42, -1.97]}
            rotation={[-Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_16"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 3.07, 3.53]}
            rotation={[0, -Math.PI / 3, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_17"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 3.07, -1.97]}
            rotation={[0, -Math.PI / 3, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_18"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 3.44, -1.97]}
            rotation={[-Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_19"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 3.07, 3.53]}
            rotation={[0, -Math.PI / 3, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_20"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[0.6, 0.77, -7.47]}
            rotation={[Math.PI, -0.47, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M3_x_05Style_1__0_21"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-3.4, 0.77, -7.47]}
            rotation={[Math.PI, -0.47, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["stand-off__0"].geometry}
            material={materials["stand-off__0"]}
            position={[-3.4, 0.05, -7.47]}
            rotation={[Math.PI, 0.25, 0]}
          />
          <mesh
            geometry={nodes["stand-off__0_1"].geometry}
            material={materials["stand-off__0"]}
            position={[0.6, 0.05, -7.47]}
            rotation={[Math.PI, 0.25, 0]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M2_x_04Style_1__0"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[5.5, 0.58, 0.73]}
            rotation={[-Math.PI, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M2_x_04Style_1__0_1"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[5.5, 0.58, 2.53]}
            rotation={[0, -Math.PI / 3, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M2_x_04Style_1__0_2"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-8.3, 0.58, 0.73]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M2_x_04Style_1__0_3"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-8.3, 0.58, 2.53]}
            rotation={[0, Math.PI / 3, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M2_x_04Style_1__0_4"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-0.65, 0.6, -4.85]}
            rotation={[-Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["ANSI_B_18241_M_-_M2_x_04Style_1__0_5"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-2.15, 0.6, -4.85]}
            rotation={[-Math.PI, -Math.PI / 6, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["DIN_EN_ISO_4762_-_M2_x_10__0_2"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-8.3, 0.14, 0.73]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes["DIN_EN_ISO_4762_-_M2_x_10__0_3"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[5.5, 0.14, 0.73]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["Screw_GB_T_138061-1992_A_M2_x_8__0"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-2.15, -0.07, -4.85]}
            rotation={[0, -1.25, Math.PI / 2]}
          />
          <mesh
            geometry={nodes["Screw_GB_T_138061-1992_A_M2_x_8__0_1"].geometry}
            material={materials["DIN_EN_ISO_4762_-_M2_x_10__0"]}
            position={[-0.68, -0.07, -4.85]}
            rotation={[0, -1.25, Math.PI / 2]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/3dModels/lineFollower/scene-transformed.glb");
